#TODAY I FORGOT TO UPLOAD THAT I LEARNED BUT I LEARN ABOUT .APPEAD OR SOMETHING LIKE THAT ALSO ABOUT .REMOVE AND HOW TO PUT ANY- 
#-VARIABLE IN A LIST ON THE START OR END OF THE LIST AND THATS ALL FOR TODAY THANKS.
